### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by X-Raym** [Percipient24/comicblind#1]
This project is interesting, it would be cool if you had any documentation to share about to make this kind of text for comics.
Thanks !

**Comment by Percipient24** [comment]
@X-Raym 

Thank you for your interest in the project!

Since you asked so nicely, I cooked up https://github.com/Percipient24/comicblind/wiki for you. As such, I'll mark this one as closed.

Feel free to ask questions / open more issues!

**Comment by Percipient24** [comment]
Merci beaucoup!

**Comment by X-Raym** [comment]
@Percipient24 Oh very nice thank you !! 🎉 I'm sure it will be useful to other users as well 👍  Thanks for the great work ! Cheers !
